# Generated by Django 3.2.4 on 2021-12-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabledoctor',
            name='time_slot',
        ),
    ]
