# Generated by Django 3.2.4 on 2021-12-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_availabledoctor_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='doc',
        ),
    ]
