# Generated by Django 3.2.4 on 2021-12-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20211222_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='booking_qrcode'),
        ),
    ]
