# Generated by Django 3.2.4 on 2021-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
