# Generated by Django 3.2.4 on 2021-12-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
