# Generated by Django 3.2.4 on 2021-12-25 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20211225_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 25, 23, 49, 49, 573443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 23, 49, 49, 573443, tzinfo=utc)),
        ),
    ]
