# Generated by Django 3.2.4 on 2021-12-25 23:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20211226_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 25, 23, 53, 40, 552323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 23, 53, 40, 552323, tzinfo=utc)),
        ),
    ]
